#!/usr/bin/env node
'use strict'

const endpoint = 'https://www.ana.co.jp/ja/jp/amc/reference/tameru/flightmile/dom/chart.html'
const ua = 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'

const cheerio = require('cheerio')
const log = require('fancy-log')
const got = require('got')
const v = require('voca')
const _ = require('lodash')
const numeral = require('numeral')

// const airports = {
// }
// const airportGroups = {
//   '東京': ['HND', 'NRT']
// }


async function fetchRawData() {
  const headers = { 'User-Agent': ua }
  const { body } = await got(endpoint, headers)
  const $ = cheerio.load(body)
  const contents = $('#contents .toggle-box')
    .toArray()
    .map(content => {
      const baseAirport = v($('h3', content).text())
        .trim()
        .replace('発着路線', '')
        .value()
      const routes = $('tr', content)
        .toArray()
        .filter(el => $('th', el).length === 0)
        .map(el => {
          const airport = v.trim($('td:first-of-type', el).text())
          const miles = $('td:nth-of-type(n+2)', el)
            .toArray()
            .map(el => v.trim($(el).text()))
            .map(text => numeral(text).value())
          return { airport, miles }
        })
      return { baseAirport, routes }
    })
  return contents
}




!async function() {
  try {
    const contents = await fetchRawData()
    console.log(contents)

  } catch (err) {
    log.error(err)
  }
}()

// vim: se sw=2 ts=2 sts=2 et ft=javascript :
